@local=http://localhost:3000/api

###
POST {{local}}/auth/register
Content-Type: application/json

{
    "fullName":"sara nagar",
    "email":"sara@gmail.com",
    "password":"Sara1234!",
    "phone":"0586633988",
    "city":"karni shomron"
}

###
POST {{local}}/auth/login/
Content-Type: application/json

{
    "email":"sara@gmail.com",
    "password":"Sara1234!"
}

###
GET {{local}}/auth/me
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM2OTNjYmIyMjc2ZWUzZWU4N2U2YzgiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU3ODUyMTA2fQ.KBehc0-_8UUztBykmlNv8QvdSGw5fkuz5sIa4SYPvgs