@local=http://localhost:3000/api

###
POST {{local}}/auth/register
Content-Type: application/json

{
    "fullName":"sara nagar",
    "email":"sara@gmail.com",
    "password":"Sara1234!",
    "phone":"0586633988",
    "city":"karni shomron"
}

###
POST {{local}}/auth/login/
Content-Type: application/json

{
    "email":"sara@gmail.com",
    "password":"Sara1234!"
}

###
GET {{local}}/auth/me
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
GET {{local}}/users/68c693cbb2276ee3ee87e6c8
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM2OTNjYmIyMjc2ZWUzZWU4N2U2YzgiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU3ODUyMTA2fQ.KBehc0-_8UUztBykmlNv8QvdSGw5fkuz5sIa4SYPvgs

###
PUT {{local}}/users/68c693cbb2276ee3ee87e6c8
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM2OTNjYmIyMjc2ZWUzZWU4N2U2YzgiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU3ODUyMTA2fQ.KBehc0-_8UUztBykmlNv8QvdSGw5fkuz5sIa4SYPvgs

{
    "fullName":"Sara noach"
}

###
DELETE {{local}}/users/68c693cbb2276ee3ee87e6c8
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
GET {{local}}/users
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
PUT {{local}}/users/68c693cbb2276ee3ee87e6c8/admin
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
POST {{local}}/requests/
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM4MWRlNGJhOGNiOTkwNmNmMjZiODIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU3OTQ4OTIwfQ.K64LumQTYTwMWkAFWxNWGSH6cVRkqDB4sHTMaujZtwA

{
    "title":"נרות",
    "description":"להדלקת נרות שבת",
    "category":"ציוד",
    "region":"דרום",
    "city":"Ashkelon"
}

###
GET {{local}}/requests/
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM4MWRlNGJhOGNiOTkwNmNmMjZiODIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU3OTQ1MzY0fQ.Q4eKno39zK_Umr0rcf0bGxuOB_Sr5lEBSnoH3rOJzlo

###
GET {{local}}/requests/68c833ca541a4493c26852f5
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM4MWRlNGJhOGNiOTkwNmNmMjZiODIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU3OTQ1MzY0fQ.Q4eKno39zK_Umr0rcf0bGxuOB_Sr5lEBSnoH3rOJzlo

###
PUT {{local}}/requests/68c82c5eb7a000bb957d450f
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM4MWRlNGJhOGNiOTkwNmNmMjZiODIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU3OTQ4OTIwfQ.K64LumQTYTwMWkAFWxNWGSH6cVRkqDB4sHTMaujZtwA

{
    "title": "גופיות ציצית"
}

###
DELETE {{local}}/requests/68c8333ccdfaa71cf1890582
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
POST {{local}}/offers/
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

{
    "title":"חולצות",
    "description":"20 חולצות קלילות ומאווררות",
    "category":"ציוד",
    "region":"צפון",
    "city":"bet shean"
}

###
GET {{local}}/offers/
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
GET {{local}}/offers/68c83acf9d31ec2ff7a91bdf

###
PUT {{local}}/offers/68c83acf9d31ec2ff7a91bdf
Content-Type: application/json
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM4MWRlNGJhOGNiOTkwNmNmMjZiODIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU3OTU0MDI4fQ.41LZ4ooVdbQATzb26PYXeNCgOHiljTc8ghTem7jT6LU

{
    "title":"חולצות גברים"
}

###
DELETE {{local}}/offers/68c83acf9d31ec2ff7a91bdf
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
PATCH {{local}}/favorites/request/68c820c533296bba00722e98
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
PATCH {{local}}/favorites/offer/68c83b0689f51e7afd2943ef
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c

###
GET {{local}}/favorites/
x-auth-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM3ZTE0NGExOWJmMjVkOTAxMTNkNjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NTc5Mjk5MjB9.KqLcmjuhl3k3GrTUoTVBWpqhZKJdUQSTJc9MjUbRN-c
